[package]
name = "autarch-vault"
version = "0.1.0"
description = "Autarch Protocol Non-Custodial Smart Vault Anchor Program on Cookie Chain"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "autarch_vault"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
solana-program = "1.18.26"
